name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
  
   name: Example
    uses: lowlighter/metrics@latest
    with:
      template: terminal
      filename: metrics.svg
      token: ${{ secrets.METRICS_TOKEN }}
      base: header, metadata
